# Generated by Django 3.2 on 2022-05-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_favorite_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_movies',
        ),
    ]
