# Generated by Django 3.2 on 2022-05-19 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20220519_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
