# Generated by Django 3.2 on 2022-05-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220519_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorite_users',
        ),
    ]
