# Generated by Django 3.2 on 2022-05-20 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_remove_movie_favorite_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
