# Generated by Django 3.2 on 2022-05-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reviews_rank_avg',
            field=models.IntegerField(default=0),
        ),
    ]
