# Generated by Django 3.2 on 2022-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_reviews_rank_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='reviews_rank_avg',
        ),
    ]
