# Generated by Django 3.2 on 2022-05-24 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0011_alter_review_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='followed_users',
            field=models.ManyToManyField(related_name='following_actors', to=settings.AUTH_USER_MODEL),
        ),
    ]
